### ISSUE TITLE
Request cold start data file

### ISSUE THREAD

**Issue by Ngqgq** [linjc16/R2-DDI#3]
Sorry to bother you, I'm reproducing the cold start task from your experiment, but I found that the following file is missing: 1.drugbank_id_smiles.csv 2.pair_pos_neg_triples-fold1-train.csv 3. pair_pos_neg_triples-fold1-s2.csv 4. pair_pos_neg_triples-fold1-s1.csv. And fold0,fold2.Could you send me if you can, I need these documents so much.

**Comment by linjc16** [comment]
1. You can use drugbank_id_smiles.csv  in transductive folder.
2,3,4 The original files comes from GMPNN [1]. For our repo, you can just run [run_binarize_unseen.sh] and [run_process_ind.py] since I have uploaded train.csv and valid.csv. 

[1] Nyamabo AK, Hui Y, Liu Z, et al. Drug–drug interaction prediction with learnable size-adaptive molecular substructures. Brief
Bioinform 2022;23(1):bbab441.

**Comment by Ngqgq** [comment]
In GMPNN-CS, through the data_preprocessing.py can only generate warm start data files, I can't find a way to generate cold start temporarily, if you can, could you provide a way to generate cold start data or tell me how to get that?
